### ISSUE TITLE
Cannot edit saved hosts

### ISSUE THREAD

**Issue by amjesus** [h3imdall/ftp-remote-edit#19] opened 2017-05-18 19:42 UTC
Hi

love your plugin but big issue since after creating the hosts cannot add or delete or change hosts since bug dont show saved, after add one new all disapear

if can solve is a 5* plug in

**Comment by h3imdall** [comment] 2017-05-19 07:10
Hi,

i can't reproduce the issue. To solve this i need more information. 
How many hosts do you have in your list? 
Since which version did the error occur the first time?
Please describe step by step the way you get the error.

**Comment by cschindl** [comment] 2017-06-10 13:10
Added dialog to change the password. To open run command "ftp-remote-edit:change-password". Empty password caused error and will no longer be accepted. Please change your password and check if the error still occurs.

**Comment by cschindl** [comment] 2017-07-24 19:41
Hi @amjesus,

unfortunately I have no feedback from you whether the changes could solve your problem. If I do not hear anything new from you, I will close this issue next week.

**Comment by amjesus** [comment] 2017-07-24 19:43
sorry for late reply
but all was fixed by your reply, i putted a password and all runs fine

great support :P

**Closed** 2017-07-24 20:05 UTC
Labels: bug
