### ISSUE TITLE
Problems handling unsaved files

### ISSUE THREAD

**Issue by ssfrr** [h3imdall/ftp-remote-edit#284] opened 2019-04-13 03:11 UTC
I've had some issues with handling unsaved files that seem like they could result in lost work.

I'm having trouble reproducing - there might be some kind of networking or SSH timeout that plays a role.

Here's the sequence of events as best I can recall:

1. connect to a remote host
2. create a new file
3. add some text and save (file is uploaded to the host)
4. make some changes but do not save
5. disconnect from network
6. save file
7. reconnect to network

At this point trying to reconnect to the remote host just displayed the spinner as if it's trying to connect, but never did. I closed Atom and re-opened it and my file was still opened, and I was able to reconnect to the host, but saving the file did not result in it getting re-uploaded to the host.

**Comment by cschindl** [comment] 2019-04-16 16:38
Hi @ssfrr,

unfortunately I cannot reproduce the error under windows. Which OS do you use? Please write your configuration here ( line command "apm -v")

**Comment by ssfrr** [comment] 2019-04-17 14:50
I'm on linux - I'll check the next time I'm at my other computer that was having the problem.

**Comment by cschindl** [comment] 2019-06-29 11:06
Hi @ssfrr,

can I close the issue here because I didn't get an answer from you?

**Comment by ssfrr** [comment] 2019-06-29 12:17
Yeah, sorry I haven't gotten to this. Feel free to close and I'll re-open if I can reproduce

**Closed** 2019-06-29 13:32 UTC
Labels: bug, needs-reproduction
