### ISSUE TITLE
Problem opening a file / timeout per FTP with Atom 1.39.0

### ISSUE THREAD

**Issue by dezmar93** [h3imdall/ftp-remote-edit#306] opened 2019-07-24 06:44 UTC
Hello,

I have a problem with your plugin ftp-remote-edit for the atom text editor. I already used the plugin for two months and it worked like a charm, but today, I get an error when I try to open a file.  As you can see here I get this error: https://ibb.co/Fg5TbPN

I did not change anything and my colleague uses with the same plugin at the same ftp server and it works fine.

Could you please help me finding a solution?

Thanks
Martin

**Comment by nagadas** [comment] 2019-07-24 15:33
Me too ...

Somebody help me how to do it.

**Comment by cschindl** [comment] 2019-07-24 20:22
Hi @dezmar93, @nagadas,

To help you, I'd need to know if you connects via ftp or sftp and a log of the debug protocol (see debug mode) would be great. To enable the debug mode please go to the atom settings and look for the package "ftp-remote-edit". Here you have to click on settings. Please activate the checkbox for debug mode. Then you can open the console via the menu "View" -> "Developer" -> "Toggle Developer Tools". The debug messages should be displayed in the console.

**Comment by dezmar93** [comment] 2019-07-24 20:39
Hi @cschindl ,

the connection is via ftp. As you can see in the attached image, i get these output when I activate the debug mode.
![Unbenannt](https://user-images.githubusercontent.com/31649094/61826908-b731cb80-ae63-11e9-81a8-b371a7ab7c47.PNG)

Does this help you? My colleague has the exact same settings and works on the same server but doesn't get these errors. On his PC everything works fine with the ftp-rremote-edit

**Comment by cschindl** [comment] 2019-07-24 20:53
The server throws a timeout. Could your firewall or Something else be blocking the connection?

**Comment by dezmar93** [comment] 2019-07-25 05:45
I deactivated the windows defender firewall but it did not help. Me and my colleague (and hon his computer everything works fine) are in the same network, so i don't think something is blocking the connection.

**Comment by chrion02** [comment] 2019-07-25 06:26
I got the exact same issue after updating atom yesterday. Something broke the addon

**Comment by cschindl** [comment] 2019-07-25 06:41
Since atom version 1.39.0 downloading via FTP doesn't work correctly anymore.  Electron and Node were updated by the upgrade. I think the bug will occur in conjunction with Node 10.2.0.

**Comment by dezmar93** [comment] 2019-07-25 07:05
Ok so are you keeping in mind that problem and comment here when there is a new version?

**Comment by andrenalin282** [comment] 2019-07-25 07:33
Same Problem to me, since 1.39.0 ftp download very slow or break, only file download affected, opening and scrolling folders is fast as always.

**Comment by piotr-lesisz** [comment] 2019-07-25 08:28
The same problem, but not on all ftp servers.

**Comment by b0li** [comment] 2019-07-25 08:55
same problem... how roll back to previous version (1.38.2) Mac?

**Comment by piotr-lesisz** [comment] 2019-07-25 09:46
After reinstall to 1.38.2 (Windows 10) - all works great!

**Comment by nagadas** [comment] 2019-07-26 12:48
Where do I download the 1.38.2 version for mac?

**Comment by piotr-lesisz** [comment] 2019-07-26 12:50
Here:  <https://github.com/atom/atom/releases/tag/v1.38.2> https://github.com/atom/atom/releases/tag/v1.38.2

 

Piotrek

**Comment by Aprania** [comment] 2019-07-26 22:38
All downloads and uploads/saves from SFTP work full correctly ever from ever. (Only for confirm @cschindl)

**Comment by MaHi84** [comment] 2019-07-27 13:19
Same here (Atom 1.39.1), it's extremely slow…

**Comment by cschindl** [comment] 2019-07-27 21:57
I was able to reproduce the error. Unfortunately this is caused by the used FTP library, which even in the current version doesn't seem to work with node 10. However, I found an FTP library that works with node 10 and later. So I have to change the whole FTP logic, which can take some time. I try my best to do this quickly.

**Comment by mpaun** [comment] 2019-07-29 11:22
Just in case, @cschindl . I updated ftp-remote to 0.16.4 version. But it didn't help for me.

**Comment by dezmar93** [comment] 2019-07-30 06:16
@cschindl I also uptated to version 0.16.4 but I still get the same error

**Comment by cschindl** [comment] 2019-07-30 06:55
Fixed in release [0.17.0](https://github.com/h3imdall/ftp-remote-edit/releases/tag/v0.17.0).

**Closed by cschindl** 2019-07-30 06:55 UTC
Labels: bug

**Comment by dezmar93** [comment] 2019-07-30 06:59
@cschindl Thanks, now it works!

**Comment by mpaun** [comment] 2019-07-31 21:46
@cschindl Thank you so much!
