### ISSUE TITLE
Last Update Crashes Atom

### ISSUE THREAD

**Issue by defrinex** [h3imdall/ftp-remote-edit#310] opened 2019-07-27 21:01 UTC
I don't know why but last update makes Atom crash when you connect to a server inside a folder.

Steps:
> open some folder
> connect to server inside that folder
> close connection
> wait 10-15 second
> crash

**Comment by defrinex** [comment] 2019-07-27 21:05
Looks like its not related to folders but Simple FTP connection. No problem with SFTP but connecting to FTP makes it crash.

**Comment by cschindl** [comment] 2019-07-27 22:00
Hi @defrinex,

I was able to reproduce the error. Apparently a crash occurs when a timeout is thrown, which is currently the case in the new atom version with FTP connections. (#306 ) Since I have to change the used FTP library, I will fix the bug as well.

**Comment by WiseEagle** [comment] 2019-07-28 09:27
We very wait new update)

**Comment by Tabwire** [comment] 2019-07-29 03:49
Same happens here, but while in a server. It just crashes randomly, even when I'm not using the editor at all.

**Comment by cschindl** [comment] 2019-07-29 07:36
Fixed in release [0.16.4](https://github.com/h3imdall/ftp-remote-edit/releases/tag/v0.16.4).

**Closed by cschindl** 2019-07-29 07:36 UTC
Labels: bug
